### ISSUE TITLE
Add CI configuration for this repository

### ISSUE THREAD

**Issue by NadiaHG** [ipa320/rosgraph_monitor#2]
Add to a new file under `.github/workflows/build.yml` the content:

```
name: CI
on: [push, pull_request]
jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic}
          - {ROS_DISTRO: noetic}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
```
